services:
  gioer.server.mongo:
    image: mongo:8.0.3
    restart: always
    container_name: "gioer-server_mongoDb"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - gioer_server_data:/data/db

volumes:
  gioer_server_data:
